Repository op-rs/maili, pull requests merged in 2025-01, with the labels that each got.

#6 chore: Maili Re-export Crate
  crates/maili/Cargo.toml
  crates/maili/README.md
  crates/maili/src/lib.rs
Labels: C-chore, C-port

#4 chore: Cargo Manifest Cleanup
  Cargo.toml
Labels: C-chore, C-deps

#8 release: 0.1.0
  CHANGELOG.md
Labels: C-release

#9 chore: Crate Shields
  README.md
Labels: C-chore

#11 chore: Fix README Shields
  README.md
Labels: C-bug, C-docs

#19 fix(docs): Update `maili-registry` version in readme
  crates/registry/README.md
Labels: C-docs

#17 chore(meta): Update issue template to include provider
  .github/ISSUE_TEMPLATE/FEATURE-FORM.yml
Labels: A-meta

#24 chore(rpc): Migrate `alloy-rs/op-alloy-rpc-jsonrpsee`->`op-rs/maili-rpc-jsonrpsee`
  Cargo.toml
  crates/rpc-jsonrpsee/Cargo.toml
  crates/rpc-jsonrpsee/README.md
  crates/rpc-jsonrpsee/src/lib.rs
  crates/rpc-jsonrpsee/src/traits.rs
Labels: A-rpc

#26 chore(docs): Update doc headers
  crates/registry/src/lib.rs
  crates/rpc-types-engine/src/lib.rs
Labels: C-bug, C-docs

#15 chore: Document Crate Releases
  RELEASES.md
Labels: C-chore, C-docs

#13 fix(protocol): Channel ID Randomization
  Cargo.toml
  crates/protocol/Cargo.toml
  crates/protocol/src/channel_out.rs
Labels: A-protocol, C-bug

#25 chore(deps): bump op-alloy to 0.9.2
  Cargo.toml
Labels: C-deps

#28 perf(rpc): Smol perf improvement `SupervisorApi`, pass slice instead of vec as param
  crates/rpc-jsonrpsee/src/traits.rs
Labels: A-rpc

#29 release: 0.1.1
  CHANGELOG.md
  Cargo.toml
  crates/provider/Cargo.toml
  crates/rpc-types-engine/Cargo.toml
Labels: C-release

#34 fix(maili): Missing Crates
  Cargo.toml
  crates/common/README.md
  crates/maili/Cargo.toml
  crates/maili/README.md
  crates/maili/src/lib.rs
Labels: C-chore

#32 fix: Add Crates to no_std Checks
  scripts/check_no_std.sh
Labels: C-chore, A-meta

#38 fix(no-std): Fix broken test in `no_std` `maili-protocol`
  crates/protocol/Cargo.toml
Labels: A-protocol, C-bug, C-deps, A-test

#31 release: 0.1.2
  CHANGELOG.md
  Cargo.toml
Labels: C-chore, C-release

#37 chore(rpc): Migrate json types from `op-alloy`
  .github/ISSUE_TEMPLATE/FEATURE-FORM.yml
  Cargo.toml
  crates/common/src/superchain.rs
  crates/maili/Cargo.toml
  crates/maili/src/lib.rs
  crates/rpc-jsonrpsee/Cargo.toml
  crates/rpc/Cargo.toml
  crates/rpc/README.md
  crates/rpc/src/api.rs
  crates/rpc/src/js_types/config.rs
  crates/rpc/src/js_types/mod.rs
  crates/rpc/src/js_types/net.rs
  crates/rpc/src/js_types/output.rs
  crates/rpc/src/js_types/safe_head.rs
  crates/rpc/src/js_types/sync.rs
  crates/rpc/src/lib.rs
Labels: A-rpc

#39 feat(protocol): L1BlockInfo Accessors
  crates/protocol/src/info/variant.rs
Labels: A-protocol, C-feat

#44 release: 0.1.3
  CHANGELOG.md
Labels: C-release

#48 chore(provider): Shrink scope of `OpEngineApi` to encompass only non-l1 methods
  crates/provider/Cargo.toml
  crates/provider/src/ext/engine.rs
Labels: A-provider

#50 chore: Submodule Sync
  .github/workflows/sync.yml
Labels: A-registry, C-chore

#51 chore: Readme Badge
  README.md
Labels: C-chore, A-rpc

#52 chore: Issue Tracking
  .github/ISSUE_TEMPLATE/BUG-FORM.yml
  .github/ISSUE_TEMPLATE/FEATURE-FORM.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: C-chore

#56 chore(provider): Export `EngineExtApi` from crate root
  crates/provider/src/ext/mod.rs
  crates/provider/src/lib.rs
Labels: A-provider

#57 chore(docs): Update docs to include rpc
  README.md
  book/src/starting.md
Labels: C-docs, A-rpc

#41 chore(genesis): Migrate genesis types from `op-alloy`
  .github/ISSUE_TEMPLATE/FEATURE-FORM.yml
  Cargo.toml
  README.md
  book/src/starting.md
  crates/genesis/Cargo.toml
  crates/genesis/README.md
  crates/genesis/src/addresses.rs
  crates/genesis/src/chain.rs
  crates/genesis/src/genesis.rs
  crates/genesis/src/lib.rs
  crates/genesis/src/params.rs
  crates/genesis/src/rollup.rs
  crates/genesis/src/system.rs
  crates/maili/Cargo.toml
  crates/maili/src/lib.rs
  crates/protocol/Cargo.toml
  crates/protocol/examples/batch_to_frames.rs
  crates/protocol/examples/frames_to_batch.rs
  crates/protocol/src/batch/core.rs
  crates/protocol/src/batch/inclusion.rs
  crates/protocol/src/batch/reader.rs
  crates/protocol/src/batch/single.rs
  crates/protocol/src/batch/span.rs
  crates/protocol/src/block.rs
  crates/protocol/src/channel_out.rs
  crates/protocol/src/compression/brotli/compress.rs
  crates/protocol/src/compression/brotli/decompress.rs
  crates/protocol/src/compression/variant.rs
  crates/protocol/src/info/variant.rs
  crates/protocol/src/utils.rs
  crates/registry/Cargo.toml
  crates/registry/README.md
  crates/registry/src/lib.rs
  crates/registry/src/superchain.rs
  crates/registry/src/test_utils/base_mainnet.rs
  crates/registry/src/test_utils/base_sepolia.rs
  crates/registry/src/test_utils/op_mainnet.rs
  crates/registry/src/test_utils/op_sepolia.rs
Labels: A-genesis

#60 chore(deps): Bump `op-alloy` to 0.9.3
  Cargo.toml
  crates/protocol/Cargo.toml
  crates/protocol/src/batch/span.rs
Labels: C-deps

#59 chore(protocol): Replace use of `OpTxType` in `maili-protocol`
  crates/protocol/Cargo.toml
  crates/protocol/src/batch/span.rs
Labels: A-protocol, C-deps

#61 chore(deps): Replace `OpTxEnvelope` with `TxEnvelope`
  crates/protocol/src/batch/transactions.rs
  crates/protocol/src/batch/tx_data/eip1559.rs
  crates/protocol/src/batch/tx_data/eip2930.rs
  crates/protocol/src/batch/tx_data/legacy.rs
  crates/protocol/src/batch/tx_data/wrapper.rs
  crates/protocol/src/block.rs
  crates/protocol/src/info/variant.rs
Labels: A-protocol, C-deps

#62 Migrate `TxDeposit` from `op-alloy`
  Cargo.toml
  crates/common/Cargo.toml
  crates/common/src/deposit/envelope.rs
  crates/common/src/deposit/mod.rs
  crates/common/src/lib.rs
  crates/protocol/Cargo.toml
  crates/protocol/examples/batch_to_frames.rs
  crates/protocol/examples/frames_to_batch.rs
  crates/protocol/src/batch/single.rs
  crates/protocol/src/batch/span.rs
  crates/protocol/src/deposits.rs
  crates/protocol/src/info/variant.rs
Labels: C-debt, C-deps

#64 chore(docs): Add missing links in book
  book/src/links.md
Labels: C-debt, C-docs

#63 chore(rpc): Remove duplicate of `maili_rpc::EngineApiExt`
  .github/workflows/ci.yml
  Cargo.toml
  README.md
  book/src/links.md
  book/src/starting.md
  crates/common/src/superchain.rs
  crates/maili/Cargo.toml
  crates/maili/src/lib.rs
  crates/protocol/Cargo.toml
  crates/protocol/src/messages/events.rs
  crates/protocol/src/messages/safety.rs
  crates/provider/Cargo.toml
  crates/provider/README.md
  crates/provider/src/ext/engine.rs
  crates/provider/src/ext/mod.rs
  crates/provider/src/lib.rs
  crates/registry/src/lib.rs
Labels: C-debt, A-rpc

#65 chore(rpc): Move `superchain` module from `maili-common`->`maili-rpc`
  crates/common/Cargo.toml
  crates/common/src/lib.rs
  crates/rpc/Cargo.toml
  crates/rpc/src/api.rs
  crates/rpc/src/js_types/mod.rs
  crates/rpc/src/js_types/superchain.rs
  crates/rpc/src/lib.rs
Labels: C-debt, A-rpc

#70 release: 0.1.5
  CHANGELOG.md
  Cargo.toml
Labels: C-release

#79 fix(ci): Fix default label in issue template `D-needs-triage`
  .github/ISSUE_TEMPLATE/FEATURE-FORM.yml
Labels: C-bug, A-meta

#73 fix: missing assets
  assets/favicon.ico
  assets/square.png
  assets/white_bg.png
Labels: C-docs

#80 chore(meta): Removes PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: A-meta

#82 fix(docs): Fix readme links
  README.md
  book/src/links.md
  crates/genesis/README.md
  crates/maili/README.md
Labels: C-bug, C-docs

#87 feat: maili-flz crate
  Cargo.toml
  crates/flz/Cargo.toml
  crates/flz/README.md
  crates/flz/src/lib.rs
  crates/protocol/Cargo.toml
  crates/protocol/src/fee.rs
  crates/protocol/src/utils.rs
Labels: C-feat

#103 feat(serde): Genericize Serialization Type
  crates/genesis/src/params.rs
  crates/registry/etc/configs.json
  crates/serde/Cargo.toml
  crates/serde/README.md
  crates/serde/src/quantity.rs
Labels: C-feat, A-serde

#107 [BOT] Update Submodules
  crates/registry/etc/configs.json
Labels: A-submodules, C-bot

#114 release: 0.1.7
  CHANGELOG.md
  Cargo.toml
Labels: C-release

#115 fix(protocol): Fix u64 return for tx size estimation
  crates/protocol/src/fee.rs
Labels: A-protocol, C-debt

#128 feat(rpc): supervisor traits + client
  Cargo.toml
  crates/interop/Cargo.toml
  crates/interop/src/derived.rs
  crates/interop/src/errors.rs
  crates/interop/src/lib.rs
  crates/interop/src/root.rs
  crates/rpc/Cargo.toml
  crates/rpc/src/lib.rs
  crates/rpc/src/supervisor.rs
Labels: C-feat, A-rpc

#126 fix(rpc): RPC Crate Cleanup
  Cargo.toml
  crates/genesis/src/chain.rs
  crates/rpc/Cargo.toml
  crates/rpc/src/api.rs
  crates/rpc/src/attributes.rs
  crates/rpc/src/js_types/config.rs
  crates/rpc/src/js_types/mod.rs
  crates/rpc/src/js_types/sync.rs
  crates/rpc/src/lib.rs
  crates/rpc/src/net.rs
  crates/rpc/src/output.rs
  crates/rpc/src/response.rs
  crates/rpc/src/superchain.rs
  crates/rpc/src/sync.rs
Labels: C-debt, A-rpc

#137 release: 0.1.8
  CHANGELOG.md
  Cargo.toml
Labels: C-release

#145 release: 0.1.10
  CHANGELOG.md
  Cargo.toml
Labels: C-chore

#144 [BOT] Update Submodules
  crates/registry/etc/configs.json
Labels: A-submodules, C-bot

#149 [BOT] Update Submodules
  crates/registry/etc/configs.json
Labels: A-submodules, C-bot
